version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: aws-0-sa-east-1.pooler.supabase.com
      DB_PORT: 6543
      DB_DATABASE: postgres
      DB_USERNAME: postgres.glroewhacscixfqjhclx
      DB_PASSWORD: maatheusdev
